---
- name: Upgrade all packages for Debian and Ubuntu systems
  apt:
    upgrade: dist
    update_cache: yes
  when: (ansible_distribution == "Debian") or
        (ansible_distribution == "Ubuntu")

- name: Refresh package cache for Centos and Fedora systems
  dnf:
    name: "*"
    state: latest
  when: (ansible_distribution == "Centos") or
        (ansible_distribution == "Fedora")

- name: Reboot the instance if required
  shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
  async: 1
  poll: 0
  ignore_errors: true
